version: "3.9"
services:
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgres:/data/postgres

    hakstore:
        build: .
        restart: unless-stopped
        ports:
            - "127.0.0.1:8954:80"
        volumes:
            - ./config.yml:/root/.config/haktools/hakstore-config.yml

volumes:
    postgres:
